#server:
#  context-path: /sell
spring:
  profiles:
    active: prod
  jackson:
    default-property-inclusion: non_null

wechat:
  mpAppId: wxd898fcb01713c658
  mpAppSecret: XXXXXXXXXXXX
  openAppId: wx6ad144e54af67d87
  openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e
  mchId: 1483469312
  mchKey: C5245D70627C1F8E9964D494B0735025
  keyPath: /var/weixin_cert/h5.p12
  notifyUrl: http://sxah.natapp1.cc/notify
  templateId:
    orderStatus: zYNAn5B_zQDn4P6n5NoB9eXf4P2ozYA5gem_FG-cbuA
logging:
  pattern:
    console: "%d - %msg%n"
  level:
    com.zlj.sell.dataobject.mapper: trace

projectUrl:
  wechatMpAuthorize: http://sxah.natapp1.cc
  wechatOpenAuthorize: http://sxah.natapp1.cc
  sell: http://sxah.natapp1.cc
  JYsell: http://sell.springboot.cn
mybatis:
  mapper-locations: classpath:mapper/*.xml




